language: python
python:
- '3.6'
- '3.5'
- '3.4'
install:
- pip install vcrpy python-coveralls pytest-cov flask elasticsearch-dsl flask_bootstrap flask-nav
script: pytest -v --cov . --cov-report term-missing
after_success: coveralls
